spring:
  application:
    name: smartproperty

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7071/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}